// Mock data for Food Ordering App (No live backend needed yet)

export const MOCK_FOOD_ITEMS = [
  {
    id: "1",
    title: "Maharashtrian Poha",
    category: "Breakfast",
    description: "Fresh, hot flattened rice seasoned with mustard seeds, roasted peanuts, and green chillies.",
    price: 80,
    image: "/images/poha.jpg",
    isPopular: true,
    rating: 4.8,
  },
  {
    id: "2",
    title: "Special Dum Biryani",
    category: "Main Course",
    description: "Aromatic basmati rice layered with authentic spices, saffron, and fresh vegetables.",
    price: 180,
    image: "/images/biryani.jpg",
    isPopular: true,
    rating: 4.9,
  },
  {
    id: "3",
    title: "Shahi Paneer Curry",
    category: "Main Course",
    description: "Soft paneer cubes simmered in a creamy, cashew-based rich tomato gravy.",
    price: 220,
    image: "/images/paneer.jpg",
    isPopular: true,
    rating: 4.7,
  },
  {
    id: "4",
    title: "Crispy Veg Burger",
    category: "Snacks",
    description: "Crispy potato veggie patty topped with fresh lettuce, tomatoes, and tangy sauce.",
    price: 120,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60",
    isPopular: false,
    rating: 4.5,
  },
  {
    id: "5",
    title: "Cheese Margherita Pizza",
    category: "Italian",
    description: "Classic hand-tossed sourdough pizza topped with mozzarella cheese and fresh basil.",
    price: 260,
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=500&auto=format&fit=crop&q=60",
    isPopular: true,
    rating: 4.9,
  },
  {
    id: "6",
    title: "Samosa Chaat (2 Pcs)",
    category: "Snacks",
    description: "Golden fried samosas mashed and topped with chickpeas curry, yogurt, and chutneys.",
    price: 90,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60",
    isPopular: false,
    rating: 4.6,
  },
];
